name: 'Checkstyle Code Analysis'
description: 'Runs Checkstyle code analysis on all modules and uploads reports'

runs:
  using: "composite"
  steps:

    - name: Run Checkstyle on All Modules (Parallel)
      if: always()
      shell: bash
      run: |
        ./gradlew \
          :clevertap-core:checkstyle \
          :clevertap-geofence:checkstyle \
          :clevertap-hms:checkstyle \
          :clevertap-pushtemplates:checkstyle \
          --parallel \
          --max-workers=4 \
          --build-cache

    - name: Upload All Checkstyle Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-reports
        path: |
          clevertap-core/build/reports/checkstyle
          clevertap-geofence/build/reports/checkstyle
          clevertap-hms/build/reports/checkstyle
          clevertap-pushtemplates/build/reports/checkstyle
