runs:
  using: "composite"
  steps:

    - name: Run Unit Tests And Code Coverage (DEBUG)
      shell: bash
      run: ./gradlew :clevertap-core:testDebugUnitTest :clevertap-geofence:testDebugUnitTest  :clevertap-hms:testDebugUnitTest  :clevertap-pushTemplates:testDebugUnitTest

    - name: Run Unit Tests And Code Coverage (RELEASE)
      shell: bash
      run: ./gradlew :clevertap-core:testReleaseUnitTest :clevertap-geofence:testReleaseUnitTest  :clevertap-hms:testReleaseUnitTest  :clevertap-pushTemplates:testReleaseUnitTest

    - name: Upload Unit tests
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: unit-tests-results
        path: |
          clevertap-core/build/reports/tests

          clevertap-hms/build/reports/tests

          clevertap-geofence/build/reports/tests

          clevertap-pushtemplates/build/reports/tests



      #todo : set success/failure as output and use slack action to send message . setting success failure: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions
