name: 'Test Coverage Comment Report'
description: 'Action that posts JaCoCo coverage reports as pull request comments'

inputs:
  github-token:
    description: 'Github token to post JaCoCo report in a PR comment'
    required: true
  baseline-branch:
    description: 'The branch to compare the JaCoCo report against'
    required: false
    default: ''
  comment-title:
    description: 'The title of the comment with the JaCoCo report'
    required: false
    default: 'Code Coverage'
  test-release:
    description: 'Run tests and code coverage for release build'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set variables
      shell: bash
      run: |
        if [ "${{ inputs.test-release }}" == 'true' ]; then
          echo "GRADLE_REPORT_TASK=jacocoTestReportRelease" >> $GITHUB_ENV
          echo "REPORT_PATH=jacocoTestReportRelease" >> $GITHUB_ENV
        else
          echo "GRADLE_REPORT_TASK=jacocoTestReportDebug" >> $GITHUB_ENV
          echo "REPORT_PATH=jacocoTestReportDebug" >> $GITHUB_ENV
        fi

    - name: Get baseline commit SHA
      if: ${{ inputs.baseline-branch != '' }}
      id: baseline-sha
      shell: bash
      run: |
        git fetch origin ${{ inputs.baseline-branch }}
        BASELINE_SHA=$(git rev-parse origin/${{ inputs.baseline-branch }})
        echo "sha=$BASELINE_SHA" >> $GITHUB_OUTPUT
        echo "Baseline branch: ${{ inputs.baseline-branch }}"
        echo "Baseline SHA: $BASELINE_SHA"

    - name: Restore baseline coverage from cache
      if: ${{ inputs.baseline-branch != '' }}
      uses: actions/cache/restore@v3
      id: baseline-cache
      with:
        path: baseline-reports/
        key: jacoco-baseline-${{ steps.baseline-sha.outputs.sha }}-${{ env.GRADLE_REPORT_TASK }}

    - name: Checkout baseline branch
      if: ${{ inputs.baseline-branch != '' && steps.baseline-cache.outputs.cache-hit != 'true' }}
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.baseline-branch }}
        path: baseline

    - name: Generate baseline JaCoCo report
      if: ${{ inputs.baseline-branch != '' && steps.baseline-cache.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: ./baseline
      run: |
        echo "📊 Generating fresh baseline report..."
        ./gradlew $GRADLE_REPORT_TASK -Pcoverage='true'
        mkdir -p ../baseline-reports
        cp -r clevertap-*/build/reports/jacoco ../baseline-reports/

    - name: Save baseline coverage to cache
      if: ${{ inputs.baseline-branch != '' && steps.baseline-cache.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v3
      with:
        path: baseline-reports/
        key: jacoco-baseline-${{ steps.baseline-sha.outputs.sha }}-${{ env.GRADLE_REPORT_TASK }}

    - name: Log cache status
      if: ${{ inputs.baseline-branch != '' }}
      shell: bash
      run: |
        if [ "${{ steps.baseline-cache.outputs.cache-hit }}" == "true" ]; then
          echo "✅ Using cached baseline for SHA: ${{ steps.baseline-sha.outputs.sha }}"
          echo "⚡ Time saved: ~8 minutes"
        else
          echo "📊 Generated fresh baseline for SHA: ${{ steps.baseline-sha.outputs.sha }}"
          echo "💾 Cached for future PRs"
        fi

    - name: JaCoCo Report
      uses: madrapps/jacoco-report@v1.7.1
      with:
        token: ${{ inputs.github-token }}
        title: ${{ inputs.comment-title }}
        paths: |
          ${{ github.workspace }}/clevertap-core/build/reports/jacoco/${{ env.REPORT_PATH }}/${{ env.REPORT_PATH }}.xml,
          ${{ github.workspace }}/clevertap-geofence/build/reports/jacoco/${{ env.REPORT_PATH }}/${{ env.REPORT_PATH }}.xml,
          ${{ github.workspace }}/clevertap-hms/build/reports/jacoco/${{ env.REPORT_PATH }}/${{ env.REPORT_PATH }}.xml,
          ${{ github.workspace }}/clevertap-pushtemplates/build/reports/jacoco/${{ env.REPORT_PATH }}/${{ env.REPORT_PATH }}.xml
        min-coverage-overall: 65
        min-coverage-changed-files: 65
        update-comment: true
        pass-emoji: '✅'
        fail-emoji: '❌'

    - name: Cleanup directories
      if: ${{ inputs.baseline-branch != '' }}
      shell: bash
      run: |
        rm -rf baseline
        rm -rf baseline-reports