inputs:
  github-token:
    description: 'Github token to post JaCoCo report in a PR comment'
    required: false
    default: ''
  baseline-branch:
    description: 'The branch to compare the JaCoCo report against'
    required: false
    default: ''

runs:
  using: "composite"
  steps:

    - name: Run All JaCoCo Test Reports (Parallel)
      if: always()
      shell: bash
      run: |
        ./gradlew \
          :clevertap-core:jacocoTestReportDebug \
          :clevertap-geofence:jacocoTestReportDebug \
          :clevertap-hms:jacocoTestReportDebug \
          :clevertap-pushtemplates:jacocoTestReportDebug \
          -Pcoverage='true' \
          --parallel \
          --max-workers=4 \
          --build-cache

    - name: Upload All Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-debug
        path: |
          clevertap-core/build/reports/tests
          clevertap-geofence/build/reports/tests
          clevertap-hms/build/reports/tests
          clevertap-pushtemplates/build/reports/tests

    - name: Upload All JaCoCo Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-reports-debug
        path: |
          clevertap-core/build/reports/jacoco
          clevertap-geofence/build/reports/jacoco
          clevertap-hms/build/reports/jacoco
          clevertap-pushtemplates/build/reports/jacoco

    - name: Post JaCoCo Report in PR comment
      if: ${{ inputs.github-token != '' }}
      uses: ./.github/mini_flows/test_coverage_report
      with:
        github-token: ${{ inputs.github-token }}
        baseline-branch: ${{ inputs.baseline-branch }}
        comment-title: 'Code Coverage Debug'
